"use client";

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: drei.lu (https://sketchfab.com/drei.lu)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/space-exploration-wlp-series-8-91964c1ce1a34c3985b6257441efa500
Title: Space exploration [WLP series #8]
*/

import React from "react";
import { useGLTF, Text3D, Center } from "@react-three/drei";
import { motion } from "framer-motion-3d";
import { useTheme } from "next-themes";
function SpaceExploration(props: any) {
  const { theme } = useTheme();

  const { nodes, materials }: any = useGLTF("/3d/space_exploration.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <motion.group
          animate={{
            scale: theme === "dark" ? 0 : 7,
            opacity: theme === "dark" ? 0 : 1,
          }}
          transition={{ duration: 1 }}
          position={[-0.003, 0.024, -6.331]}
          rotation={[0.238, -0.545, 0.562]}
        >
          <Center position={[0.84, 0.2, 0.4]} rotation={[2, 2, 0]}>
            <Text3D
              curveSegments={32}
              bevelEnabled
              bevelSize={0.02}
              bevelThickness={0.1}
              height={0}
              lineHeight={0.5}
              letterSpacing={0.04}
              size={0.15}
              font="/Inter_Bold.json"
            >
              WDS
              <meshNormalMaterial />
            </Text3D>
          </Center>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.planet001_1.geometry}
            material={materials.scene}
          />
          <mesh castShadow receiveShadow geometry={nodes.planet001_2.geometry}>
            <meshStandardMaterial
              attach="material"
              color="#ccc"
              roughness={0.5}
              metalness={0.5}
            />
          </mesh>
        </motion.group>
      </group>
    </group>
  );
}

useGLTF.preload("/3d/space_exploration.glb");
export default SpaceExploration;
